#!/bin/bash -e

# lowercase words
# tanh logistic

# iterations 10 100
# l2Regularization 0.001 0.01 0.1 1
# initialStepSize 0.1
# gaussianVariance 0.1 0.01
# vectorModelName addition sequenceRnn Birnn logicalFormNn autogeneratedLogicalFormNn
# dimensionality 100 300

ITERATIONS=(10 100)
L2_REGULARIZATION=(0.001 0.01 0.1 1)
INITIAL_STEP_SIZE=(0.1)
GAUSSIAN_VARIANCE=(0.1 0.01)
VECTOR_MODEL_NAME=(addition sequenceRnn Birnn logicalFormNn autogeneratedLogicalFormNn)
DIMENSIONALITY=(100 300)

for ITER in ${ITERATIONS[@]}; do
for L2 in ${L2_REGULARIZATION[@]}; do
for STEP in ${INITIAL_STEP_SIZE[@]}; do
for VAR in ${GAUSSIAN_VARIANCE[@]}; do
for NAME in ${VECTOR_MODEL_NAME[@]}; do
for DIM in ${DIMENSIONALITY[@]}; do
    CMD="./src/scripts/invoke.pl edu.cmu.ml.rtw.vector.VectorModelTrainer --domainDir data/cobot/set/kinect/ --trainingFilename training.annotated.txt.merged -iterations $ITER --batchSize 1 --l2Regularization $L2 --initialStepSize $STEP --logInterval 1000 --gaussianVariance $VAR --vectorModelName $NAME --dim $DIM --adagrad"

    echo $CMD
done
done
done
done
done
done