
#  --numFoldsToRun 1
<<<<<<< HEAD
./src/scripts/invoke.pl -Xmx2000M  edu.cmu.ml.rtw.vector.VectorModelTrainer --domainDir data/cobot/set/kinect/ --trainingFilename training.annotated.txt.merged -iterations 10 --batchSize 1 --l2Regularization 0.02 --initialStepSize 0.1 --logInterval 500 --gaussianVariance 0.01 --vectorModelName logicalFormNn --adagrad
=======
./src/scripts/invoke.pl -Xmx2000M  edu.cmu.ml.rtw.vector.VectorModelTrainer --domainDir data/cobot/set/kinect/ --trainingFilename training.annotated.txt.merged -iterations 10 --batchSize 1 --l2Regularization 0.02 --initialStepSize 0.1 --logInterval 500 --gaussianVariance 0.01 --vectorModelName autogeneratedLogicalFormNn --adagrad
>>>>>>> ae0d2861a07130d9fb11cae4c7e0508fc9d65b17
